#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define GAME_KEY_SEEN 1
#define GAME_KEY_DOWN 2
#define GAME_KEY_JUST_PRESSED 4

#define DISPLAY_BUFFER_WIDTH 1280//1920.0 
#define DISPLAY_BUFFER_HEIGHT 600//720//1080.0

#define DISPLAY_SCALE 1.0
#define DISPLAY_WIDTH DISPLAY_SCALE* DISPLAY_BUFFER_WIDTH
#define DISPLAY_HEIGHT DISPLAY_SCALE* DISPLAY_BUFFER_HEIGHT

#define DRAW_DECK_X DISPLAY_BUFFER_WIDTH - 150
#define DRAW_DECK_Y 400//910

#define DECK_WIDTH 80
#define DECK_HEIGHT 80


#define PLAYER_BEGIN_X 300
#define PLAYER_BEGIN_Y 100
#define PLAYER_RADIUS 100

#define HEALTH_BAR_HEIGHT 20
#define HEALTH_BAR_BACKGROUND_EXTRA 1

#define SHIELD_BAR_HEIGHT HEALTH_BAR_HEIGHT
#define SHIELD_BAR_BACKGROUND_EXTRA HEALTH_BAR_BACKGROUND_EXTRA

#define SHIELD_BAR_COLOR al_map_rgb(0, 200, 255) // Ciano/Azul claro
#define SHIELD_BAR_OFFSET 5.0f // Espaço entre a barra de vida e a de escudo

#define HEALTH_BAR_RX 0
#define HEALTH_BAR_RY 0

#define HAND_BEGIN_X 325
#define HAND_BEGIN_Y DISPLAY_HEIGHT - CARD_WIDTH - 100//300//780

#define CARD_WIDTH 140//280
#define CARD_HEIGHT 210//420

#define TAM_MAX_DECK 50
#define TAM_MAX_MAO 10
#define TAM_MAX_DECK_INIMIGO 5

#define QTD_MAX_ELIXIR 3
#define MAX_ENEMIES 2

#define DECK_Y_POS DISPLAY_BUFFER_HEIGHT - DECK_HEIGHT - 10 


#define DISCARD_DECK_X HAND_BEGIN_X - 200
#define DISCARD_DECK_Y DECK_Y_POS - 50

// You might want to use this.
typedef enum {
  MOVE_LEFT = 0,
  MOVE_RIGHT = 1,
} CursorMovementDirection;

#endif